name: Build Firmware

on:
  workflow_dispatch:
    inputs:
      config:
        description: 'Config file'
        required: true
        default: 'xiaomi/mi-mini'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo apt update
          sudo apt install -y build-essential libncurses5-dev zlib1g-dev gawk git flex bison libssl-dev
          cd trunk
          cp configs/templates/${{ github.event.inputs.config }}.config .config
          echo 'CONFIG_FIRMWARE_INCLUDE_EAP_PEAP=y' >> .config
          make V=99
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: trunk/bin/
